FROM 122137374271.dkr.ecr.ap-east-1.amazonaws.com/kconnect-nginx:latest

MAINTAINER zhangzs "zhangzs520@dingtalk.com"

EXPOSE 8080

ADD dist /data/application/dist

USER kconnect

WORKDIR /data/application
